<?php

function hello_user_menu()
{
    $items = array();
    $items['sign_up_success'] = array(
        'title' => 'Congratulations, you have signed up successfully!',
        'page callback' => 'greet_new_user',
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function greet_new_user()
{
    return '
        <p>Now you can sign yourself up for some relaxing on the beach, free boogie board rentals, and drinks at our beachside bar!</p>
    ';
}

function hello_user_user_insert()
{
    $_GET['destination'] = 'sign_up_success';
}
