<?php

    function greeting_menu()
    {
        $items = array();
        $items['hello_friend'] = array(
            'title' => 'Hello Friend',
            'page callback' => 'say_hello',
            'access callback' => True,
            'type' => MENU_CALLBACK,
        );
        $items['farewell'] = array(
            'title' => 'Goodbye dear friend',
            'page callback' => 'say_farewell',
            'access callback' => True,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function say_hello()
    {
        return '
            <h3>Hello friend, welcome!</h3>
        ';
    }

    function say_farewell()
    {
        return '
            <h3>Farewell dear friend, save travels!</h3>
        ';
    }

    function greeting_user_login()
    {
        $_GET['destination'] = 'hello_friend';
    }

    function greeting_user_logout()
    {
        $_GET['destination'] = 'farewell';
    }
